version: '3.8'
services:
  movies:
    image: abouttime1021/paymovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: abouttime1021/paytrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: abouttime1021/paycable:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: abouttime1021/payrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
